//
//  Language.swift
//  Qhome
//
//  Created by LGH419 on 7/7/19.
//  Copyright © 2019 LGH419. All rights reserved.
//

import Foundation
import UIKit

class Language: NSObject {
    var choose_lang = "choose_language".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var warning = "warning".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var producer = "producer".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var customer = "customer".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_email = "enter_email".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_name = "enter_name".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_password = "enter_password".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_phone = "enter_phone".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_instagram = "enter_instagram".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_area = "enter_area".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_street = "enter_street".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_house = "enter_house".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var select_role = "select_role".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_address = "enter_address".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter_valid_email = "enter_valid_email".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var select_2items = "select_2items".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var choose_category = "choose_category".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var filter_canceled = "filter_canceled".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var filter_applied = "filter_applied".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var profile = "profile".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var products = "products".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var rate = "rate".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var write_something = "write_something".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var write_feedback = "write_feedback".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var ratings = "ratings".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var add_product = "add_product".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var edit = "edit".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var submit = "submit".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var cart = "cart".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var wishlist = "wishlist".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    var address = "address".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var phone = "phone".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var shipping_address = "shipping_address".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter1moreshippingaddress = "enter1+shippingaddress".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enter1morephonenumber = "enter1+phonenumber".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterfullphone = "enter_full_phone".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var yes = "yes".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var save = "save".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var myname = "myname".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var instagramaccount = "instagramaccount".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var change_name = "change_name".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var change_instagram = "change_instagram".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var suredelete = "suredelete".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var loggedout = "loggedout".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var image_saved = "image_saved".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var save_error = "save_error".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var saved = "saved".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var ok = "ok".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var all = "all".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var placed = "placed".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var confirmed = "confirmed".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var prepared = "prepared".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var ready = "ready".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var delivered = "delivered".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    var confirm = "confirm".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var prepare = "prepare".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var delivery = "delivery".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var completed = "completed".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var neworders = "neworders".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var hint = "hint".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var registerstoretext = "registerstoretext".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var serverissue = "serverissue".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var verify_phone = "verify_phone".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var login_success = "login_success".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var unregistereduser = "unregistereduser".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var incorrectpassword = "incorrectpassword".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var verified = "verified".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var existingemail = "existingemail".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var existinguser = "existinguser".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var messagesent = "messagesent".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var allproducts = "allproducts".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var cancel = "cancel".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var total = "total".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var subtotal = "subtotal".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var shipping = "shipping".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var bonus = "bonus".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var updatefeedbackinstore = "updateyourfeedbackinthisstore".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var placefeedbackinstore = "placeyourfeedbackinthisstore".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var writesubject = "writesubject".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var rateoutstars = "rateoutstars".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var writefeedback = "writefeedback".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var feedbacksubmited = "feedbacksubmited".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var accountprogress = "accountprogress".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var accountprogresstext = "accountprogresstext".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    var enterstorename = "enterstorename".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterdesc = "enterdesc".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterstorenameinarabic = "enterstorenameinarabic".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterdescriptioninarabic = "enterdescriptioninarabic".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var loadlogo = "loadlogo".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var mystore = "mystore".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var food = "food".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var drinks = "drinks".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var sweets = "sweets".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var stationery = "stationery".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var accessories = "accessories".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var perfumes = "perfumes".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var others = "others".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var profileupdated = "profileupdated".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var phoneadded = "phoneadded".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var addressadded = "addressadded".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var updatefeedbackinapp = "updateyourfeedbackinthisapp".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var placefeedbackinapp = "placeyourfeedbackinthisapp".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var info_exists = "info_exists".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var sorry = "sorry".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var winner_exists = "winner_exists".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var you_won = "you_won".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var info_submited = "info_submited".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var discount = "discount".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var use_coupon = "use_coupon".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var no_coupon = "no_coupon".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var order_submited = "order_submited".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var surecancel = "surecancel".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var canceled = "canceled".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var customerordercanceled = "customerordercanceled".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var unused = "unused".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var used = "used".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var expired = "expired".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var admin = "admin".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var loadproductpictures = "loadproductpictures".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterproductname = "enterproductname".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterproductprice = "enterproductprice".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var enterproductdescription = "enterproductdescription".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var uploaded = "uploaded".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var thisstoreincludes2categories = "thisstoreincludes2categories".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var cart_empty = "cart_empty".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var wishlist_empty = "wishlist_empty".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var search = "search".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var account_deleted = "account_deleted".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var noresult = "noresult".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var entervalidnumberforprice = "entervalidnumberforprice".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    var doha30 = "doha30".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var doha50 = "doha50".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    var admin_login = "admin_login".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    var naql_company = "naql_company".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    var selectprice = "selectprice".localized(lang: UserDefaults.standard.string(forKey: "language") ?? "en")
    
    
}

extension String{
    func localized(lang:String)->String{
//        print(lang)
        let path = Bundle.main.path(forResource: lang, ofType: "lproj")
        let bundle = Bundle(path: path!)
        return NSLocalizedString(self, tableName: nil, bundle: bundle!, value: "", comment: "")
    }
}
